server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-sebteoui?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
